name: build

on:
  push:
    tags:
      - '*'
jobs:
  release_via_goreleaser:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0 # Note that this actually causes ALL refs to be fetched :S
      -
        name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: '^1.18'
      -
        name: Set up Node
        uses: actions/setup-node@v3
        with:
          node-version: '16'
      -
        name: Install goreleaser
        run: |
          go install github.com/goreleaser/goreleaser@latest
      -
        name: Build static JS file and package into templates.go
        run: |
          make all
      -
        name: Release with Goreleaser
        env:
          GITHUB_TOKEN: ${{ secrets.GH_ACCESS_TOKEN }}
        run: |
          goreleaser release

