name: build

on:
  push:
    tags:
      - '*'
# 2024-10-14: To debug this Github Action, I recommend running the `act` program like so to use a
# reasonable approximation of the Github `ubuntu-latest` image.
#     act -P ubuntu-latest=catthehacker/ubuntu:act-latest
# Note that the above will fail at the last step as `act` doesn't make the GH_ACCESS_TOKEN
# available, but it'll show that all the prior build steps work on your machine.
jobs:
  release_via_goreleaser:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0 # Note that this actually causes ALL refs to be fetched :S
      -
        name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: '^1.18'
      -
        name: Set up Node
        uses: actions/setup-node@v3
        with:
          node-version: '16'
      -
        name: Update CA dependencies
        run: |
          sudo update-ca-certificates
      -
        name: Install goreleaser
        run: |
          go install github.com/goreleaser/goreleaser@latest
      -
        name: Build static JS file and package into templates.go
        run: |
          make all
      -
        name: Release with Goreleaser
        env:
          GITHUB_TOKEN: ${{ secrets.GH_ACCESS_TOKEN }}
        run: |
          goreleaser release

